#!/usr/bin/env python3
"""
Quick Email Reply - Generate simple replies without Qwen.

Usage:
    python email_reply_quick.py ./AI_Employee_Vault
"""

import sys
import logging
from pathlib import Path
from datetime import datetime

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger('Quick Email Reply')


def generate_simple_reply(email_content: str) -> dict:
    """Generate a simple acknowledgment reply."""
    # Parse email
    lines = email_content.split('\n')
    from_email = ''
    subject = ''
    
    for line in lines:
        if line.lower().startswith('from:'):
            from_email = line.split(':', 1)[1].strip()
        elif line.lower().startswith('subject:'):
            subject = line.split(':', 1)[1].strip()
    
    # Generate template reply
    return {
        'subject': f'Re: {subject}',
        'body': f'''Dear Sender,

Thank you for your email.

We have received your message and will respond within 24 hours.

Best regards,
AI Employee'''
    }


def create_approval_file(vault_path: Path, email_file: Path, reply: dict) -> Path:
    """Create approval request file."""
    content = email_file.read_text(encoding='utf-8')
    
    # Parse metadata
    metadata = {}
    lines = content.split('\n')
    in_frontmatter = False
    for line in lines:
        if line.strip() == '---':
            in_frontmatter = not in_frontmatter
        elif in_frontmatter and ':' in line:
            key, value = line.split(':', 1)
            metadata[key.strip()] = value.strip()
    
    from_email = metadata.get('from', 'sender@example.com')
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    approval_content = f'''---
type: approval_request
action: email_send
to: {from_email}
subject: {reply['subject']}
original_file: {email_file.name}
created: {datetime.now().isoformat()}
status: pending
---

# Approval Required: Send Email Reply

**To:** {from_email}

**Subject:** {reply['subject']}

---

## Reply Body

{reply['body']}

---

## Original Email

**From:** {from_email}
**Subject:** {metadata.get('subject', 'No Subject')}

---

## To Approve

Move this file to `/Approved` folder

---

*Generated by AI Employee*
'''
    
    approval_file = vault_path / 'Pending_Approval' / f'EMAIL_reply_{timestamp}.md'
    approval_file.write_text(approval_content, encoding='utf-8')
    
    return approval_file


def main():
    if len(sys.argv) < 2:
        print("Usage: python email_reply_quick.py <vault_path>")
        sys.exit(1)
    
    vault_path = Path(sys.argv[1]).resolve()
    email_folder = vault_path / 'Needs_Action' / 'email'
    
    if not email_folder.exists():
        logger.info("No email folder")
        return
    
    # Find unprocessed emails
    emails = [f for f in email_folder.iterdir() 
              if f.is_file() and f.suffix == '.md' and not f.name.startswith('.')]
    
    if not emails:
        logger.info("No emails to process")
        return
    
    logger.info(f"Found {len(emails)} email(s)")
    
    for email_file in emails:
        logger.info(f"Processing: {email_file.name}")
        
        content = email_file.read_text(encoding='utf-8')
        reply = generate_simple_reply(content)
        
        approval_file = create_approval_file(vault_path, email_file, reply)
        logger.info(f"Created: {approval_file.name}")
        
        # Move original to Done
        dest = vault_path / 'Done' / email_file.name
        email_file.rename(dest)
        logger.info(f"Moved to Done: {dest.name}")


if __name__ == '__main__':
    main()
